### ISSUE TITLE
Setting rtx.fallbackLightMode = 0 causes an error on load

### ISSUE THREAD

**Issue by yohjimane** [NVIDIAGameWorks/dxvk-remix#13]
### Software information
Stalker Call Of Pripyat, using OpenXray engine. [Setup instructions](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-RTX-Remix-setup-for-debugging)

### System information
GPU: MSI 3080 10gb
Driver: 531.68
DXVK version: https://github.com/NVIDIAGameWorks/dxvk-remix/commit/733ca1820eaf81365a5c995d138cc149c39bae83

### Reproduction steps
1. Manually add fallbackLightMode = 0 to rtx.conf, or do it through remix ui `dev menu > game setup > parameter tuning > light translation > Fallback Light Mode = "Never"`
2. Start the game
3. Game does not load

![efb1672f467d40105d8ad147252d5fd6](https://user-images.githubusercontent.com/11345783/235430680-d5a85c15-aedb-49b6-999a-0c7323810656.png)

### Log files

[xray_engine log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11364460/openxray_nguye.log)
[xrEngine_d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11364462/xrEngine_d3d9.log)

**Comment by AlexDunn** [comment]
Good find!!  I've put a fix in here for this issue: https://github.com/NVIDIAGameWorks/dxvk-remix/commit/27b628486fd3dda2d1d2315a7c967f44438032ae

**Comment by yohjimane** [comment]
> Good find!! I've put a fix in here for this issue: [27b6284](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/27b628486fd3dda2d1d2315a7c967f44438032ae)

I tested this fix using latest release ([7b3884a](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/7b3884a9e8006bf084fb02e7b652af0b9410e011)). This issue seems to be resolved now :) 

Thank you @AlexDunn!
