### ISSUE TITLE
Shadows render incorrectly when perspective correction is enabled

### ISSUE THREAD

**Issue by yohjimane** [NVIDIAGameWorks/dxvk-remix#19]
### Software information
- Stalker Call Of Pripyat, using OpenXray engine. [Setup instructions](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-RTX-Remix-setup-for-debugging)

### System information
- GPU: MSI 3080 10gb
- Driver: 531.68
- DXVK version: [7b3884a](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/7b3884a9e8006bf084fb02e7b652af0b9410e011)

### Reproduction steps
- Observe shadows without weapon equipped
  - Looks correct
- Observe shadows with weapon equipped and perspective correction = on
  - Looks incorrect. The shadow angle changes and shadows can now move around based on camera movement.
- Observe shadows with weapon equipped and perspective correction = off
  - Looks correct

### Notes:
- STALKER uses two variables for FOV, one is for the world FOV and one is for the viewmodel FOV. 
- World FOV can change when using magnified scopes to aim.
- Viewmodel FOV can vary based on what item you have equipped.

### Log files
[xrEngine_d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11458826/xrEngine_d3d9.log)

### Video of bug
[1080p version here](https://streamable.com/6y2p87)

https://github.com/NVIDIAGameWorks/dxvk-remix/assets/11345783/a370c41b-5961-434b-b938-18c507869230

**Comment by sultim-t-nv** [comment]
Interesting, it seems cameras are detected incorrectly. There are `rtx.viewModel.maxZThreshold` and `rtx.skyMinZThreshold` options that might be worth tweaking. Just need to wait for GitHub Actions fix on the latest builds to be able to download latest builds...

**Comment by sultim-t-nv** [comment]
Yup, the [build](https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/5511789687) is ready now.

**Comment by yohjimane** [comment]
@sultim-t-nv sorry for such a late reply!

I just checked out the latest branch, and updated the configs. The values that seemed to fix the issue for OpenXRay are below:
```
rtx.skyMinZThreshold = 0.005
rtx.viewModel.maxZThreshold = 0.027
```

https://github.com/NVIDIAGameWorks/dxvk-remix/assets/11345783/baf9d844-496f-4378-8467-663b44631176

Thank you for fixing this!
