### ISSUE TITLE
A few issues with Iron Storm

### ISSUE THREAD

**Issue by VoxelArtist** [NVIDIAGameWorks/dxvk-remix#21]
In Iron Storm(2005) I'm having 2 main issues. I'm unable to add lights to textures using remix. The textures flash green in game when I hover over them in the remix menu but does nothing when I select the texture. The second issue I think is a result of the first issue where depending on where I'm looking, a random light will appear behind me. I assume this is a back up light being added by remix due to remix not detecting any other lights. Using "In View Transform" seems to change that but also adds a really bad looking motion blur effect that I'm unsure is intended or not. Motion blur is turned off in game and in remix post processing. 

In the discord I saw that someone else is having a similar issue with the lighting in Return to Castle Wolfenstein if that is easier to take a look at.

Apologize if any info is missing or if my issues aren't clear. Please let me know if I need to expand on anything
### Software information
Iron Storm, settings in video are all on but still occurs when everything is low/off 

### System information
- GPU:RTX 3080 FE
- Driver:531.79
- DXVK version: 538155a

### Log files
[d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11501816/d3d9.log)
[IronStorm_d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11501817/IronStorm_d3d9.log)

https://github.com/NVIDIAGameWorks/dxvk-remix/assets/112427434/fa7e23eb-611c-40c4-8d6f-1f47b90a313c

**Comment by NV-DM** [comment]
Hi. Typically replacing emissive texture requires authoring of new textures as emissive. Using in-game albedo as emissive is not expected to work very well. Please refer to the Discord community for further help. https://discord.gg/rtxremix
