### ISSUE TITLE
Can't build DXVK-Remix with gametargets.conf

### ISSUE THREAD

**Issue by AndreyRGW** [NVIDIAGameWorks/dxvk-remix#3]
Can't build DXVK-Remix with gametargets.conf

### Software information
GTA:SA, changed paths in gametargets.conf

### System information
- GPU: RTX 2060 12Gb
- Driver: 531.29
- Windows version: Windows 11 22H2

### Log files
- [build.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11253505/build.log)
- [meson-log.txt](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11253556/meson-log.txt)

**Comment by jamesrtyrrell** [comment]
I think this is what happened to me, you need to unzip the Remix Zip to the root directory of your game. I don't think that is made very clearly in the doc to be fair. 

[https://github.com/NVIDIAGameWorks/rtx-remix/wiki/runtime-user-guide](https://github.com/NVIDIAGameWorks/rtx-remix/wiki/runtime-user-guide)

**Comment by NV-DM** [comment]
@AndreyRGW the guidance posted by @jamesrtyrrell seems to be correct. Closing based on that. If you still have problems please ping this ticket again.
