### ISSUE TITLE
Build status badge link directs to 404

### ISSUE THREAD

**Issue by svelle** [NVIDIAGameWorks/dxvk-remix#4]
https://github.com/NVIDIAGameWorks/dxvk-remix/blob/1c1b6c6409de3a79425757fc12357614a19bc469/README.md?plain=1#L3

This line is linking to a 404 (at least as a user outside of the org that doesn't have access to actions)

I think if it would link to https://github.com/NVIDIAGameWorks/dxvk-remix/blob/main/.github/workflows/build.yml instead, it would work for any users. 

I would've opened a PR, but I'm not too knowledgeable about your build pipeline so I wanted to create an issue first.

**Comment by apanteleev** [comment]
Fixed by enabling Actions on the repo.

**Comment by svelle** [comment]
awesome, thanks!
