### ISSUE TITLE
[REMIX-2074] Crash in GTA:SA

### ISSUE THREAD

**Issue by baazthefalcon** [NVIDIAGameWorks/dxvk-remix#41]
Before I was on DXVK build 222 and Bridge build 28, did not update to the latest build for around 2 3 days, everything was running fine until I updated to DXVK 236 and Bridge 29. Its started doing memory overload then crashes then I tested backwards till DXVK build 232 every build crashed same way. Then I found a fixed it on DXVK build 236 By lowering the max resolution which i belive was tanking the memory. Then Few hours DXVk Build 240 came, in between i had a doubt on Bridge build 29 with build 28 it was ok but was crashing with 29. Then DXVK Build 242 Came with Bridge Build 28 also crashed.

### Software information
Game - GTA San Andreas  ver1.0 USA,
In Game Setting - Frame Limiter On, Widescreen - On, Visual Quality - High, Mipmap - No, Anti Aliasing - No , Resolution - 1600x900

### System information
- GPU: Galax RTX 2060 Super
- Driver: 537.13
- Bridge Remix: Build 28 same on 29, before it gave me long error log which i posted on Discord general too
- DXVK Remix:  build 242

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: 
[d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/12563560/d3d9.log)

- gta-sa_d3d9.log:
[gta-sa_d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/12563574/gta-sa_d3d9.log)
[gtasa_logs.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/12563578/gtasa_logs.log)

- NvRemixBridge.log:
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/12563593/NvRemixBridge.log)

Before  
If i missed anything please ask

**Comment by achtchaern** [comment]
Just curious: What does this have to do with Opacity Micropmaps? I thought this feature requires an Ada Lovelace GPU?

**Comment by pkristof** [comment]
Please attach a crash dump. According to your NvRemixBridge.log you can find it here:
 Saving minidump to 'E:\Games\GTA - The Original Trilogy\GTASA\.trex\NvRemixBridge.exe_20230909_013248.dmp'

**Comment by pkristof** [comment]
> Just curious: What does this have to do with Opacity Micropmaps? I thought this feature requires an Ada Lovelace GPU?
Opacity Micromaps are supported on previous generation architecture (i.e. Ampere) as well. But based on the bug description and the issue being present in build 232 it doesn't sound like an OMM issue since OMMs got reenabled by default only in build 234. Crash dump should tell us more the reason behind the crash.

**Comment by baazthefalcon** [comment]
i made it zip still cant upload

**Comment by pkristof** [comment]
Yes the crash happens in a location unrelated to OMMs. Can you rename the ticket to `Crash in GTA SA`
