### ISSUE TITLE
Shadows move with Camera in GTA San Andreas

### ISSUE THREAD

**Issue by baazthefalcon** [NVIDIAGameWorks/dxvk-remix#44]
So, having a problem with camera at night specifically in gta san andreas wheres as shadows move with camera movement, if i change the fuse mode then shadows move with player movement...sometimes happens in day too as i keep changing settings

What I Understand - This game also uses emesives as remix try to not show lights while those are rasterized emmesive or coronas which  remix cant read because its not a proper light... Hence having weird lighting issuse at night because as per the game lights gets enabled at night.

Provided a Video Link from Discord for better understanding whats the issue.
https://discord.com/channels/1028444667789967381/1028444668918235197/1152992716393820170

### Software information
Game - GTA San Andreas ver1.0 USA,
In Game Setting - Frame Limiter On, Widescreen - On, Visual Quality - High, Mipmap - No, Anti Aliasing - No , Resolution - 1600x900

### System information
- GPU: RTX 2060 Super
- Driver: 537.34
- Bridge version: Build 29
- DXVK version: Build 248

### Log files
[d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/12644862/d3d9.log)
[gta-sa_d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/12644863/gta-sa_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/12644865/NvRemixBridge.log)

**Comment by achtchaern** [comment]
Video link does not work. Maybe consider uploading your video on a publicly accessible location (YouTube?)

**Comment by baazthefalcon** [comment]
https://drive.google.com/file/d/1yVzENLlQLo_ZCmYwez_5sA1KzmqNSTNV/view?usp=sharing

**Comment by nv-ajaus** [comment]
@baazthefalcon Can you please try this with the most recent builds of dxvk-remix and bridge-remix?

**Comment by nv-ajaus** [comment]
@baazthefalcon it's been a few weeks since I reached out, so I'm going to go ahead and close this issue. Please feel free to file a new issue under https://github.com/NVIDIAGameWorks/rtx-remix/issues if you want to look at into this again. Thank you!
