### ISSUE TITLE
A list of errors given on lego lotr

### ISSUE THREAD

**Issue by usermaf** [NVIDIAGameWorks/dxvk-remix#45]
1. There's a load of  DirectInput: unable to translate VSC: 203, 200, 205 and 208 errors in the d3d9 log.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2. In the <game name> d3d9 log there's these:
--> info:  [RTX-Compatibility-Info] Trying to raytrace but not detecting a valid camera.
--> warn:  D3D9Texture2D::QueryInterface: Unknown interface query
--> warn:  794950f2-adfc-458a-905e-10a10b0b503b
(here's the full log: 
[LEGOLOTR_d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/12725732/LEGOLOTR_d3d9.log)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

3. There's nothing in the bridge log that gives a warn.

**Comment by nv-ajaus** [comment]
Hi @usermaf , other than the warning message, is there a noticeable symptom in the game you are trying?

**Comment by usermaf** [comment]
a load of smearing, due to shader removal. (not the smearing from the game being rasterized) *this issue is also present when removing the shaders with the reshade shader removal tool} {i could assume it may be something to do with the ingame aa, or something}

no camera detected issue.

cubemap reflections still intact.

**Comment by NV-DM** [comment]
Hi @usermaf for bring up of RTX Remix with a particular game I would recommend reaching out to the community discord server ( https://discord.gg/rtxremix ).
